name: test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test coverage
              run: |
                npm ci
                npm test -- --coverage